version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest
      JWT_PUBLIC_KEY: /keys/public.pem
      JWT_PRIVATE_KEY: /keys/private.pem
    ports:
      - "5432:5432"
    volumes:
      - ./keys:/keys
      - .:/app
    command: ["sh", "-c", "sleep 5 && npm run start:dev"]

volumes:
  mongo_data:
